name: Cypress Tests
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix: 
        containers: [1, 2]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Start Web App FrontEnd
        run: |
          cd web
          npm install
          npm start &

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          spec: |
            cypress/e2e/cadastro-sucesso.cy.js
            cypress/e2e/login-clinica.cy.js
            cypress/e2e/dashboard.cy.js
          wait-on: 'http://localhost:3000,https://vollmecypress-server-1.onrender.com'
          record: true
          parallel: true
          group: 'Cypress Tests'

        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}