name: Cypress Tests
on:
  push:
    branches: [ testes ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # Instala e inicia o FRONT local (ajuste o diretório!)
      - name: Install front
        working-directory: web
        run: npm ci

      - name: Run Cypress (start + wait-on)
        uses: cypress-io/github-action@v6
        with:
          working-directory: web
          start: npm start
          wait-on: |
            http://localhost:3000
            https://vollmecypress-server-1.onrender.com
          wait-on-timeout: 120
          spec: |
            cypress/e2e/cadastro-sucesso.cy.js
            cypress/e2e/login-clinica.cy.js
            cypress/e2e/dashboard.cy.js
          record: true
          parallel: true
          group: 'Cypress Tests'
        env:
          API_URL: https://vollmecypress-server-1.onrender.com
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
